# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rbd-pvc-sc-demo
  namespace: demo
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
